# Generated by Django 3.0.3 on 2020-08-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('apelido', models.CharField(blank=True, max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
